### PR TITLE
Feature: Implement a non-observable error API

### PR DESCRIPTION
**Pull request by ScottMGerstl**
- This simplifies the API by removing the need for the async pipe as a standard though it is still supported.
- Documentation and demos updated

### CODE REVIEW

**Comment by EndyKaufman** [comment]
if open page and toch to inputs errors not shows :(
image

**Comment by ScottMGerstl** [comment]
Can you explain the desired behavior? I'll code it to match the criteria. I was guessing a little on what things should be doing.

If I know how or should behave, I can start writing tests too.
________________________________

**Comment by EndyKaufman** [comment]
sorry it's my bug :) manual testing...

**Comment by ScottMGerstl** [comment]
Ah. Ok :)
________________________________

**Pull request merged**
