### PR TITLE
Feat: Option allowing to specify which nested models to create + limit recursive model generation 

### PR DESCRIPTION
**Pull request by jbjhjm**
As discussed in https://github.com/EndyKaufman/ngx-dynamic-form-builder/issues/185
here is my proposal for implementation of controlling which and how many nested models should be created.

In order to implement the needed changes, I first had to do small tweaks before:

* lib was getting reference to class-transformer/validator storage from window. This does not work in jest/node env, so it was updated to use the getGlobal() function.
* tsconfig.spec.json has been updated to allow jest tests to run correctly. 
* I'm not fast with cypress, so I added jest tests based on the runner that nx already provides.

Regarding the implementation, I think the commits speak for themselves, refer to the tests and updated readme to see how it is working.

### CODE REVIEW

**Comment by jbjhjm** [comment]
I guess cypress tests are failing because of the introduced nested model limit that is right now defaulting to 2 levels of nesting.

**Comment by EndyKaufman** [comment]
@jbjhjm in my head the implementation is different) more like how it was before when you can assign angular validators and at the same time the structure of the form controls is described

**Comment by jbjhjm** [comment]
@EndyKaufman Your implementation concept may be beneficial, it could easily be extended later if more detailed configuration per prop is required, while mine is only a list of switch states.
Use any of the added logic that is useful for you :)

I unfortunately am in a bad hurry right now so I'll go with my implementation even if it is just for some days or weeks.

**Comment by EndyKaufman** [comment]
@jbjhjm yes of course, I forgot about the global - thanks, the implementation of the nesting limit will be almost the same - thanks
I will write in this MR when I make edits

Thanks for your work 👍

**Comment by jbjhjm** [comment]
thank you as well @EndyKaufman !

**Comment by EndyKaufman** [comment]
https://github.com/EndyKaufman/ngx-dynamic-form-builder/pull/191

**Pull request closed without merging**
